SELECT 
    B.CATEGORY,
    SUM(TOTAL_BOOK_SALES) AS TOTAL_SALEWS
FROM BOOK AS B
INNER JOIN 
    (SELECT 
        BOOK_ID, 
        SUM(SALES) AS TOTAL_BOOK_SALES 
     FROM BOOK_SALES 
     WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
     GROUP BY BOOK_ID) AS T
 ON T.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
    
